# ==================================================================== #
#               KONFIGURASI PLUGIN RPG IDENTITY CARD                   #
# ==================================================================== #

header:
  kingdom: "KERAJAAN VALORIA - KARTU IDENTITAS RPG"
  city: "KOTA ATLANTA CENTRAL"
  status_berlaku: "SEUMUR HIDUP"

security:
  secret_key: "ValoriaSecretKey2026"

messages:
  prefix: "&8[&b&lIDENTITY&8] &r"
  no_id_self: "&cKamu belum mendaftar Kartu Identitas! Membuka formulir..."
  no_id_other: "&cPemain &e%player% &cbelum mendaftar Kartu Identitas."
  registration_success: "&a&lSELAMAT! Kartu Identitas kamu berhasil diterbitkan secara resmi."
  give_card_success: "&aBerhasil mengambil Fisik Kartu Identitas milik &e%nama%&a!"
  show_card_sender: "&aKamu menunjukkan Kartu Identitas milikmu kepada &e%target%&a!"
  show_card_receiver: "&e%sender% &amenunjukkan Kartu Identitas miliknya kepadamu:"
  card_locked: "&cKartu Identitas kamu sudah diterbitkan secara resmi dan dikunci! Hubungi Admin jika ingin mengubah data."

item:
  use_custom_map: false
  material: "PAPER"
  custom_model_data: 20001
