# ======================================================
#            RPG IDENTITY CARD CONFIGURATION
# ======================================================

card:
  kingdom: "&b&lKERAJAAN VALDORA"
  city: "&7KOTA VALORIA"
  status_berlaku: "&a&lSEUMUR HIDUP"
  secret_key: "VALDORA-SECRET-SIGNATURE-2026"

messages:
  prefix: "&8[&bIDENTITY&8] "
  no_id_self: "&cKamu belum mendaftarkan Kartu Identitas! Menampilkan form pendaftaran..."
  no_id_other: "&c%player% belum memiliki Kartu Identitas Resmi!"
  registration_success: "&aKartu Identitas Resmi milikmu telah berhasil terbit!"
  give_card_success: "&aBerhasil mengambil Fisik Kartu Identitas milik &e%nama%&a!"
  show_card_sender: "&aKamu menunjukkan Kartu Identitas milikmu kepada &e%target%&a."
  show_card_receiver: "&e%sender% &atelah menunjukkan Kartu Identitas miliknya kepadamu."
  card_locked: "&cKartu Identitas kamu sudah terbit dan terkunci! Hanya Admin yang dapat me-edit data ini."

item:
  material: "PAPER"
  custom_model_data: 900001
  player_card_cmd_start: 900100
  use_custom_map: false
  auto_iazip: true

economy:
  enabled: true
  cost: 100
  take_command: "economy take %player% %cost%"
  paid_success_msg: "&aBiaya penerbitan KTP sebesar &e%cost% Koin &atelah dipotong!"
  insufficient_funds_msg: "&c&l[❌] Koin kamu tidak cukup! Kamu membutuhkan &e%cost% Koin &cuntuk membuat KTP!"
